all:
  children:
    jalenmaklamp:           ## this is group called jalenmaklamp
      hosts:
        webserver:
          ansible_host: 10.0.2.24     ## this is the node IP
    ## follow the same pattern to add a new group
    ## this is a group with SINGLE node only,  
    

## if you need to have a group with bunches of nodes,can change here
## updte the /etc/hosts so that Ansible Master can map the domain name <-> IP address
# all:
#   children:
#     jalenmaklamp:        ## we have a group called jalenmaklamp
#       hosts:
#         wordpress.local:
#         movie.local:
    
#     dextermak:           ## we have another group called dextermak
#        hosts: 
#          music.local:
#          file.local:
         

# # My example 
# all:
#   children:
#     jalenmak:
#       hosts:
#         web1:
#           ansible_host: 192.168.1.81
#         web2:
#           ansible_host: 192.168.1.83
